# Generated by Django 5.0.3 on 2024-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50, null=True)),
                ('Department', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
