# Generated by Django 5.0.4 on 2024-04-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customet_user',
            name='user_typr',
            field=models.CharField(choices=[('jobrecruiter', 'JobRecuiter'), ('jobseeker', 'JobSeeker')], max_length=50),
        ),
    ]
