# Generated by Django 5.0.4 on 2024-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customet_user_user_typr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customet_user',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customet_user',
            name='Blood',
            field=models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customet_user',
            name='DOB',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customet_user',
            name='Gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customet_user',
            name='Image',
            field=models.ImageField(null=True, upload_to='Jobportal/image'),
        ),
        migrations.AlterField(
            model_name='customet_user',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customet_user',
            name='user_typr',
            field=models.CharField(choices=[('jobrecruiter', 'JobRecuiter'), ('jobseeker', 'JobSeeker')], max_length=50, null=True),
        ),
    ]
