# Generated by Django 5.0.3 on 2024-04-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_teachermodel_timage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='DImage',
            field=models.ImageField(null=True, upload_to='media/Doctor_Image'),
        ),
    ]
