# Generated by Django 5.0.3 on 2024-03-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(max_length=50, null=True)),
                ('DDepartment', models.CharField(max_length=50, null=True)),
                ('DCity', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=50, null=True)),
                ('TDepartment', models.CharField(max_length=50, null=True)),
                ('TCity', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
