# Generated by Django 5.1 on 2024-08-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=100, null=True)),
                ('Institution', models.CharField(max_length=100, null=True)),
                ('GraduationYear', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePicture', models.ImageField(null=True, upload_to='static/ProfilePic')),
                ('FullName', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Phone_number', models.CharField(max_length=100, null=True)),
                ('EmailAddress', models.CharField(max_length=100, null=True)),
                ('CareerObjective', models.TextField(null=True)),
                ('HardSkills', models.CharField(max_length=100, null=True)),
                ('SoftSkills', models.CharField(max_length=100, null=True)),
                ('Certifications', models.CharField(max_length=100, null=True)),
                ('Projects', models.CharField(max_length=100, null=True)),
                ('References', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100, null=True)),
                ('Position', models.CharField(max_length=100, null=True)),
                ('StartDate', models.CharField(max_length=100, null=True)),
                ('EndDate', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
