# Generated by Django 5.1 on 2024-08-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumemodel',
            old_name='Phone_number',
            new_name='PhoneNumber',
        ),
    ]
