# Generated by Django 5.0.3 on 2024-04-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_doctormodel_dimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='DImage',
        ),
    ]
