# Generated by Django 5.0.4 on 2024-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=50, null=True)),
                ('Institution', models.CharField(max_length=50, null=True)),
                ('Graduationyear', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profilepicture', models.ImageField(null=True, upload_to='resume/ProfilePicture')),
                ('FullName', models.CharField(max_length=50, null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('PhoneNumber', models.CharField(max_length=50, null=True)),
                ('EmailAddress', models.CharField(max_length=50, null=True)),
                ('CareerObjective', models.CharField(max_length=50, null=True)),
                ('Certifications', models.TextField()),
                ('Projects', models.CharField(max_length=50, null=True)),
                ('References', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoftSkills', models.CharField(max_length=50, null=True)),
                ('HardSkills', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=50, null=True)),
                ('Position', models.CharField(max_length=50, null=True)),
                ('StartDate', models.CharField(max_length=50, null=True)),
                ('EndDate', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
