# Generated by Django 5.0.7 on 2024-08-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_resumemodel_careerobjective_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationModel',
        ),
        migrations.DeleteModel(
            name='SkillsModel',
        ),
        migrations.DeleteModel(
            name='WorkModel',
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='Company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='Degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='EndDate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='Graduationyear',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='HardSkills',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='Institution',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='Position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='SoftSkills',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='StartDate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
