# Generated by Django 5.0.3 on 2024-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name11', models.CharField(max_length=20)),
                ('blid', models.CharField(max_length=20)),
            ],
        ),
    ]
