# Generated by Django 5.0.4 on 2024-04-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_custom_user_dob_custom_user_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='address',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
