# Generated by Django 5.0.4 on 2024-04-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_custom_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='blood',
            field=models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=50, null=True),
        ),
    ]
