# Generated by Django 5.0.4 on 2024-04-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_custom_user_blood_alter_custom_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Job_Recruiter')], max_length=50, null=True),
        ),
    ]
