# Generated by Django 5.0.3 on 2024-03-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatemodel',
            old_name='language',
            new_name='languages',
        ),
    ]
