# Generated by Django 5.0.3 on 2024-03-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_subjectmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='classModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name4', models.CharField(max_length=20)),
                ('classid', models.CharField(max_length=50)),
            ],
        ),
    ]
