# Generated by Django 5.0.7 on 2024-08-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Picture', models.ImageField(null=True, upload_to='media/ProfilePic')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Profession1', models.CharField(max_length=100, null=True)),
                ('Profession2', models.CharField(max_length=100, null=True)),
                ('Profession3', models.CharField(max_length=100, null=True)),
                ('Aboutdetails', models.CharField(max_length=500, null=True)),
                ('ProfessionTitle1', models.CharField(max_length=100, null=True)),
                ('ProfessionTitle2', models.CharField(max_length=100, null=True)),
                ('ProfessionDetails', models.TextField(null=True)),
                ('ProfessionPara', models.TextField(null=True)),
                ('Birthday', models.CharField(max_length=100, null=True)),
                ('Website', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fact', models.TextField(null=True)),
                ('HappyClients', models.CharField(max_length=100, null=True)),
                ('Projects', models.CharField(max_length=100, null=True)),
                ('SuppotTime', models.CharField(max_length=100, null=True)),
                ('HardWorkers', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientTestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(max_length=100, null=True)),
                ('ClientPic', models.ImageField(null=True, upload_to='media/ClientPic')),
                ('ClientProfession', models.CharField(max_length=100, null=True)),
                ('ClientReview', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactDetails', models.TextField(null=True)),
                ('ContactLocation', models.CharField(max_length=100, null=True)),
                ('ContactEmail', models.CharField(max_length=100, null=True)),
                ('ContactCall', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portfolio', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationName', models.CharField(max_length=100, null=True)),
                ('EducationYear', models.CharField(max_length=100, null=True)),
                ('EducationInstitute', models.CharField(max_length=100, null=True)),
                ('EducationDetails', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.TextField(null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('About', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Mobile', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeProExModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfessionalExperience', models.CharField(max_length=100, null=True)),
                ('ProfessionalYear', models.CharField(max_length=100, null=True)),
                ('ProfessionalLocation', models.CharField(max_length=100, null=True)),
                ('ProfessionalResponsibilities', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.CharField(max_length=100, null=True)),
                ('ServiceName', models.CharField(max_length=100, null=True)),
                ('ServiceDetails', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillMatricesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.CharField(max_length=100, null=True)),
                ('SkillProgress', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('Instagram', models.CharField(max_length=100, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonial', models.TextField(null=True)),
            ],
        ),
    ]
