# Generated by Django 5.0.7 on 2024-08-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_socialmediamodel_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediamodel',
            name='Instagram',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='twitter',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
