# Generated by Django 5.0.4 on 2024-04-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('company_description', models.CharField(max_length=50, null=True)),
                ('job_description', models.CharField(max_length=50, null=True)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('salary', models.CharField(max_length=50, null=True)),
                ('joiningdate', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
