# Generated by Django 5.0.4 on 2024-04-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50, null=True)),
                ('recipe_category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=50, null=True)),
                ('tags', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('nonvegetarian', 'NonVegetarian')], max_length=50, null=True)),
                ('recipe_title', models.CharField(max_length=50, null=True)),
                ('ingredients', models.CharField(max_length=50, null=True)),
                ('instruction', models.CharField(max_length=50, null=True)),
                ('prep_time', models.CharField(max_length=50, null=True)),
                ('cooking_time', models.CharField(max_length=50, null=True)),
                ('total_time', models.CharField(max_length=50, null=True)),
                ('nutritional_info', models.CharField(max_length=50, null=True)),
                ('sample_image', models.ImageField(null=True, upload_to='static/RecipeImage')),
                ('total_calories', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
