# Generated by Django 5.0.4 on 2024-04-29 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_recipemodel_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='chefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=50, null=True)),
                ('skills', models.CharField(max_length=50, null=True)),
                ('resume', models.CharField(max_length=50, null=True)),
                ('Profile_Picture', models.ImageField(max_length=50, null=True, upload_to='static/Profile_Picture')),
                ('myUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Picture', models.ImageField(max_length=50, null=True, upload_to='static/Profile_Picture')),
                ('Favourite', models.CharField(max_length=50, null=True)),
                ('myUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
