# Generated by Django 5.0.4 on 2024-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chefprofile_viewerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='Profile_Picture',
            field=models.ImageField(null=True, upload_to='static/Profile_Picture'),
        ),
        migrations.AlterField(
            model_name='viewerprofile',
            name='Profile_Picture',
            field=models.ImageField(null=True, upload_to='static/Profile_Picture'),
        ),
    ]
